[package]
name = "knarkos"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
spin = "0.9.8"
volatile = "0.2.6"
bootloader = "0.9.23"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
