name: Publish knarkos

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v18

      - name: Build knarkos
        run: nix develop --command cargo build --release

      - name: Determine commit hash
        id: commit_hash
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.commit_hash.outputs.commit_hash }}
          release_name: ${{ steps.commit_hash.outputs.commit_hash }}
          draft: false
          prerelease: false

      - name: Upload knarkos binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/x86_64-knarkos/release/knarkos
          asset_name: knarkos
          asset_content_type: application/octet-stream
